// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function sum(l) {
  if (l) {
    return l[0] + sum(l[1]) | 0;
  } else {
    return 0;
  }
}

exports.sum = sum;
/* No side effect */
